whole app
serejabogdan/task1-form pull request #2
Opened 2021-08-04 12:02 UTC by serejabogdan

added redux, saga, react-router-dom, connected-react-router, axios, redux-form
made pages - sign-in form and user information
added app initializing

2021-08-04 12:29 UTC, zanusilker requested changes

2021-08-04 12:29 UTC, zanusilker commented on src/components/input-field/index.js
> +  disabled: PropTypes.bool
add isRequired props

2021-08-04 12:29 UTC, zanusilker commented on src/components/preloader/index.js
> +import React from 'react';
Use reactstrap Spinner

2021-08-04 12:29 UTC, zanusilker commented on src/components/user-data/index.js
> +        <ListGroupItem>id: { id }</ListGroupItem>
```suggestion
        <ListGroupItem>id: { user.id }</ListGroupItem>
```

2021-08-04 12:29 UTC, zanusilker commented on src/index.css
> +    text-align: center;
```suggestion
```

2021-08-04 12:29 UTC, zanusilker commented on src/index.js
>  import React from 'react';
// outsource dependencies

2021-08-04 12:29 UTC, zanusilker commented on src/index.js
> +import './index.css';
// local dependencies

2021-08-04 12:29 UTC, zanusilker commented on src/pages/index.js
> +import React, { useEffect } from 'react';
🌲

2021-08-04 12:29 UTC, zanusilker commented on src/pages/index.js
> +  const { initialized } = useSelector(state => state.root.pagesInitialize);
const selector = state => state.root.pagesInitialize

2021-08-04 12:29 UTC, zanusilker commented on src/pages/index.js
> +          <Route exact path="/" render={() => <Redirect to="/public"/>}/>
```suggestion
          <Redirect to="/public"/>
```

2021-08-04 12:29 UTC, zanusilker commented on src/pages/private/user/index.js
> +  return (
```suggestion
  return 
```

2021-08-04 12:29 UTC, zanusilker commented on src/pages/public/index.js
> +      <Route path="/public/sign-in" component={PublicForm}/>
routes as constants

2021-08-04 12:29 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +  const { initialValues: { client } }
```suggestion
  const { initialValues }
```

2021-08-04 12:29 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +  const { disabled } = useSelector(state => state.root.pagesInitialize);
use redux store for sign-in page

2021-08-04 12:29 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +      <FormGroup>
InputField -> FormGroup``

2021-08-04 12:29 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +  switch (action.type) {
Create META type

2021-08-04 12:29 UTC, zanusilker commented on src/pages/public/sign-in/saga.js
> +    const UNAUTHORIZED = 401;
```suggestion
```

2021-08-04 12:29 UTC, zanusilker commented on src/pages/public/sign-in/sign-in.css
> +    display: flex;
```suggestion
```

2021-08-04 12:29 UTC, zanusilker commented on src/pages/reducer.js
> +  errorMessage: 'Something wrong',
```suggestion
  errorMessage: '',
```

2021-08-04 12:29 UTC, zanusilker commented on src/pages/saga.js
> +import { delay } from '../utils/API';
delay  from 'redux-saga/effects'

2021-08-04 12:29 UTC, zanusilker commented on src/utils/API.js
> +      Authorization: `Bearer ${token}`
https://github.com/axios/axios#config-defaults

2021-08-04 12:29 UTC, zanusilker commented on src/utils/form-validators.js
> +    return undefined;
```suggestion
    return null;
```

2021-08-04 12:29 UTC, zanusilker commented on src/utils/form-validators.js
> +export const maxLength15 = maxLengthCreator(15);
```suggestion
```

2021-08-05 13:18 UTC, zanusilker requested changes

2021-08-05 13:18 UTC, ichabanivan commented on src/components/input-field/index.js
> +  return (
```suggestion
  return <FormGroup>
```

2021-08-05 13:18 UTC, ichabanivan commented on src/components/input-field/index.js
> +  id: PropTypes.string,
```suggestion
  name: PropTypes.string.isRequired,
```

2021-08-05 13:18 UTC, ichabanivan commented on src/components/preloader/index.js
> +  return <Spinner color="primary" />;
Use it directly in the code

2021-08-05 13:18 UTC, ichabanivan commented on src/components/user-data/index.js
> +        <ListGroupItem><img src={user.coverImage.url} alt=""/></ListGroupItem>
alt

2021-08-05 13:18 UTC, ichabanivan commented on src/components/user-data/index.js
> +  })
required

2021-08-05 13:18 UTC, ichabanivan commented on src/pages/index.js
> +import { PRIVATE, PUBLIC } from '../utils/constants';
```suggestion
import { PRIVATE, PUBLIC } from '../constants';
```

2021-08-05 13:18 UTC, ichabanivan commented on src/pages/reducer.js
> +export function getPagesData () {
```suggestion
export function getPagesData (state) {
```

2021-08-05 13:18 UTC, ichabanivan commented on src/pages/reducer.js
> +  return state => state.root.pagesData;
```suggestion
  return state.root.pagesData;
```

2021-08-05 13:18 UTC, ichabanivan commented on src/pages/private/index.js
> +  const privateState = useSelector(getPrivateState());
```suggestion
  const { initialized } = useSelector(getPrivateState());
```

2021-08-05 13:18 UTC, ichabanivan commented on src/pages/private/reducer.js
> +export const PRIVATE_META = 'PRIVATE_META';
```suggestion
export const META = '@private/META';
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/private/saga.js
> +import { PRIVATE_USER, PUBLIC_SIGN_IN } from '../../utils/constants';
```suggestion
import { PRIVATE_USER, PUBLIC_SIGN_IN } from '../../constants/routes.js';
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/private/saga.js
> +function * gettingUserDataWorker (action) {
```suggestion
function * gettingUserDataWorker ({ type, payload }) {
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/private/saga.js
> +}
```suggestion
yield put({ type: PRIVATE_META, payload: { initialized: true } });
}
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/private/user/index.js
> +  return <UserData user={user}/>
why it is another component?

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/index.js
> +      <Route path={PUBLIC_SIGN_IN} component={SignUp}/>
```suggestion
      <Route path={PUBLIC_SIGN_UP} component={SignUp}/>
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/index.js
> +      <Route path={PUBLIC_SIGN_IN} component={PublicForm}/>
```suggestion
      <Route path={PUBLIC_SIGN_IN} component={SignIn}/>
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/reducer.js
> +
```suggestion
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/saga.js
> +    data: { ...payload }
```suggestion
    data: payload
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/saga.js
> +    yield call([localStorage, localStorage.setItem], 'token', response.data.accessToken);
```suggestion
    yield call(localStorage.setItem, 'token', response.data.accessToken);
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/saga.js
> +export function getTokenFromApi (payload) {
move too sign-in page

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +    dispatch({ type: SAGA_SET_TOKEN, payload: submitData });
```suggestion
    dispatch({ type: SAGA_SET_TOKEN, payload: { client, ...values } });
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +import 'bootstrap/dist/css/bootstrap.min.css';
// styles

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +      <UserFormRedux onSubmit={submit}/>
why does it another component?

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +const loginInitialState = {
```suggestion
const initial = {
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +export function getClient () {
```suggestion
export function selector () {
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +  return state => state.root.pages.public.signin.initialValues.client;
```suggestion
  return state => state.root.pages.public.signin
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/reducer.js
> +  accessToken: localStorage.getItem('token') || '',
```suggestion
  token: localStorage.getItem('token') || '',
```

2021-08-05 13:18 UTC, zanusilker commented on src/pages/saga.js
> +  try {
get token from localstorage

2021-08-05 13:18 UTC, zanusilker commented on src/utils/API.js
> +    privateAPI.defaults.headers.common.Authorization = `Bearer ${token}`;
initialize on pages saga

2021-08-09 09:53 UTC, zanusilker commented on src/pages/index.js
> +import { Spinner } from 'reactstrap';
// outsource dependencies

2021-08-09 09:53 UTC, zanusilker commented on src/pages/index.js
> +import { selector, PAGES } from './reducer';
🌲

2021-08-09 09:54 UTC, zanusilker commented on src/pages/index.js
> +      dispatch({ type: 'STOP_REFRESHING_TOKEN' });
use constants

2021-08-09 09:54 UTC, zanusilker commented on src/pages/index.js
> +  return <>
```suggestion
  return 
```

2021-08-09 09:55 UTC, zanusilker commented on src/pages/private/index.js
> +import { Spinner } from 'reactstrap';
?

2021-08-09 09:55 UTC, zanusilker commented on src/pages/private/index.js
> +        <PrivateRoute path={PRIVATE_USER} isUserAuthed={!!root.pagesData.user}
```suggestion
        <PrivateRoute 
        path={PRIVATE_USER} 
        isUserAuthed={!!root.pagesData.user}
```

2021-08-09 09:56 UTC, zanusilker commented on src/pages/private/index.js
> +import { selector } from '../../redux/reducer';
```suggestion
import { selector as privateSelector } from '../../redux/reducer';
```

2021-08-09 09:57 UTC, zanusilker commented on src/pages/private/reducer.js
> +    VALID_TOKEN: `${prefix}VALID_TOKEN`
where do you use it?

2021-08-09 09:58 UTC, zanusilker commented on src/pages/private/saga.js
> +import { addAuthorizationHeader, getUserData, privateAPI } from '../../utils/API';
extract user request to this file

2021-08-09 09:59 UTC, zanusilker commented on src/pages/private/user/index.js
> +import { SAGA_LOGOUT } from './reducer';
?

2021-08-09 10:00 UTC, zanusilker commented on src/pages/private/user/index.js
> +    dispatch({ type: SAGA_LOGOUT });
```suggestion
    dispatch({ type: TYPE.SAGA_LOGOUT });
```

2021-08-09 10:00 UTC, ichabanivan commented on src/pages/private/user/index.js
> +      <ListGroupItem><img src={user.coverImage.url} alt="Here is should be user"/></ListGroupItem>
```suggestion
      <ListGroupItem>
      <img src={user.coverImage.url} alt="Here is should be user"/>
      </ListGroupItem>
```

2021-08-09 10:01 UTC, zanusilker commented on src/pages/private/user/reducer.js
> +export const SAGA_LOGOUT = 'SAGA_LOGOUT';
PRIVATE

2021-08-09 11:31 UTC, zanusilker commented on src/pages/index.js
> +    </Switch> : <div><Spinner color="primary" /> pages</div>;
```suggestion
    </Switch> 
    : <div>
    <Spinner color="primary" />
     pages
     </div>;
```

2021-08-09 11:32 UTC, zanusilker commented on src/pages/private/index.js
> +        component={User}/>
```suggestion
        component={User}
        />
```

2021-08-09 11:32 UTC, zanusilker commented on src/pages/private/index.js
> +        user={user}
🌲

2021-08-09 11:34 UTC, zanusilker commented on src/pages/public/saga.js
> +function * publicPagesWatcher () {}
```suggestion
```

2021-08-09 11:34 UTC, zanusilker commented on src/pages/public/saga.js
> +  yield fork(publicPagesWatcher);
```suggestion
```

2021-08-09 11:36 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +    dispatch({ type: SIGN_IN.SET_TOKEN, payload: { client: signIn.initialValues.client, ...values } });
```suggestion
    dispatch({ type: TYPE.SIGN_IN, payload: { client: signIn.initialValues.client, ...values } });
```

2021-08-09 11:37 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +    <ReduxForm form="SignInForm" onSubmit={submit} validate={formValidation}>
```suggestion
    <ReduxForm form="SignInForm" onSubmit={submit} validate={formValidation} initialValues={signIn.data}>
```

2021-08-09 11:37 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +  disabled: false
initialized
errorMessage

2021-08-09 11:38 UTC, zanusilker commented on src/pages/saga.js
> +
```suggestion
```

2021-08-09 11:38 UTC, zanusilker commented on src/pages/saga.js
> +
```suggestion
```

2021-08-09 11:39 UTC, zanusilker commented on src/utils/private-route.js
> +  return (
```suggestion
  return 
```

2021-08-09 11:40 UTC, zanusilker commented on src/utils/private-route.js
> +        isUserAuthed ? <Component {...props} {...rest} /> : <Redirect to="/public/sign-in" />
Can you do it on layout level?

2021-08-10 09:29 UTC, merged